### ISSUE TITLE
HI,How does the topk_pos_neg_iu_xray.json file come about? How can I generate my own topk_pos_neg_iu_xray.json file?

### ISSUE THREAD

**Issue by shenshaowei** [Bhanu068/ITHN#3]
How does the **topk_pos_neg_iu_xray**.json file come about? How can I generate my own **topk_pos_neg_iu_xray.json** file?

**Comment by Bhanu068** [comment]
Hello,

I don't have the related Python script now but I have updated the annotation file with a correct copy which should work without any issues. Please use this file - data/iu_xray/updated_top1_pos_neg_reports.json

**Comment by shenshaowei** [comment]
> 你好
> 
> 我现在没有相关的 Python 脚本，但我已经使用正确的副本更新了注释文件，它应该可以正常工作，没有任何问题。请使用此文件 - data/iu_xray/updated_top1_pos_neg_reports.json

No, the data I'm using is not from chest X-rays, and my application task is not on chest X-rays, but I would like to test the effectiveness of this method. Could you please provide the code used to generate this data? Thank you very much.
